version: 2
jobs:
  build:
    docker:
      - image: node:12.14.1

    dependencies:
      pre:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

    steps:
      - checkout

      - run: npm ci

      - save_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}
          paths:
            - node_modules

  deploy:
    docker:
      - image: node:12.14.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}

      - run: npx semantic-release

  lint:
    docker:
      - image: node:12.14.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}

      - run: npm run lint

  test:
    docker:
      - image: node:12.14.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}

      - run: npm run test

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context: reaction-publish-semantic-release
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          context: reaction-publish-semantic-release
          requires:
            - lint
            - test
          filters:
            branches:
              only: trunk
